#ifndef _SYSTEM_CALLS_H
#define _SYSTEM_CALLS_H

#define SYSCALL_EXIT 0
#define SYSCALL_WAIT 1
#define SYSCALL_SPAWN 2
#define SYSCALL_REGISTER 3
#define SYSCALL_CONNECT 4
#define SYSCALL_SELECT 5
#define SYSCALL_READ 6
#define SYSCALL_WRITE 7
#define SYSCALL_MMAP 8

#endif
