#ifndef _SYSTEM_CALLS_H
#define _SYSTEM_CALLS_H

#define SYSCALL_EXIT 0
#define SYSCALL_WAIT 1
#define SYSCALL_PIDOF 2
#define SYSCALL_REGISTER 3
#define SYSCALL_READ 4
#define SYSCALL_WRITE 5
#define SYSCALL_MMAP 6
#define SYSCALL_HANDLE 7
#define SYSCALL_PEEK 8

#endif
